apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ear-trainer
  annotations:
    github.com/project-slug: SG60/ear-trainer
spec:
  type: other
  lifecycle: unknown
  owner: main
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ear-trainer-supabase-db
spec:
  type: database
  owner: main
  system: ear-trainer
---
