name: Adds all issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/SG60/projects/7
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          # labeled: bug, needs-triage
          # label-operator: NOT
